---
- name: Test nginx config
  command: "{{ nginx_test_command }}"
  listen: restart nginx

- name: restart nginx
  service:
    state: restarted
    name: "{{ nginx_service_name }}"
  listen: restart nginx
